# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'LargeImageViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LargeImageViewer
pod 'ALCameraViewController'
pod 'arek', '~> 2.0.2'

end
